version: '2'
services:
  proxysql:
    image: proxysql/proxysql:latest
    ports:
      - 3306:3306
      - 6033:6033
    container_name: proxysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=proxysqluser
      - MYSQL_PASSWORD=proxysqlpwd
  mysql1:
    image: mysql
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DATABASE=sample
    volumes:
     - "./scripts/mysql1.sql:/docker-entrypoint-initdb.d/init_script.sql"
  mysql2:
    image: mysql
    ports:
     - 3308:3306
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DATABASE=sample
    volumes:
     - "./scripts/mysql2.sql:/docker-entrypoint-initdb.d/init_script.sql"
