version: '2'
services:
  proxysql:
    image: proxysql/proxysql:latest
    ports:
      - 3306:3306
      - 6033:6033
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=proxysqluser
      - MYSQL_PASSWORD=proxysqlpwd
  mysql1:
    image: mysql
    ports:
     - 3307:3306
    build:
      context: mysql1
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DATABASE=sample
  mysql2:
    image: mysql
    ports:
     - 3308:3306
    build:
      context: mysql2
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DATABASE=sample
